<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_FLTRELE_entry__img lazyloaded</name>
   <tag></tag>
   <elementGuidId>cff62059-bf27-4b5c-ab34-d43e52c20971</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-container']/div/div/div/div/article/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.entry__img.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.iletisim.gov.tr/images/uploads/icerik/_toplu/Irk%C3%A7%C4%B1l%C4%B1kTwit00.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entry__img lazyloaded</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;col-lg-12 blog__content mb-72&quot;]/div[@class=&quot;row card-row&quot;]/div[@class=&quot;col-md-4&quot;]/article[@class=&quot;entry card&quot;]/div[@class=&quot;entry__img-holder card__img-holder&quot;]/a[1]/div[@class=&quot;thumb-container thumb-70&quot;]/img[@class=&quot;entry__img lazyloaded&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div/div/div/div/article/div/a/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.iletisim.gov.tr/images/uploads/icerik/_toplu/Irk%C3%A7%C4%B1l%C4%B1kTwit00.jpg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
   </webElementXpaths>
</WebElementEntity>
