<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ins_STOK DURUMU_iCheck-helper</name>
   <tag></tag>
   <elementGuidId>8f52c8ad-7773-4997-805d-d81066f9a2da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.icheckbox_flat-grey.hover > ins.iCheck-helper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dv_87678202']/div/label/div/ins</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ins</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iCheck-helper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dv_87678202&quot;)/div[@class=&quot;form-check form-check-inline&quot;]/label[@class=&quot;hover&quot;]/div[@class=&quot;icheckbox_flat-grey hover&quot;]/ins[@class=&quot;iCheck-helper&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_87678202']/div/label/div/ins</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label/div/ins</value>
   </webElementXpaths>
</WebElementEntity>
