<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_letiim Bakanl_entry__img lazyloaded</name>
   <tag></tag>
   <elementGuidId>3514250b-8a4b-4fee-aff6-10eacae6623d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-container']/div/div/div/div[2]/article/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.iletisim.gov.tr/images/uploads/icerik/_ikili/ee575f47-6128-45bc-bcf1-7720d9bfe44d_1.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entry__img lazyloaded</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;col-lg-12 blog__content mb-72&quot;]/div[@class=&quot;row card-row&quot;]/div[@class=&quot;col-md-6&quot;]/article[@class=&quot;entry card&quot;]/div[@class=&quot;entry__img-holder card__img-holder&quot;]/a[1]/div[@class=&quot;thumb-container thumb-50&quot;]/img[@class=&quot;entry__img lazyloaded&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div/div/div/div[2]/article/div/a/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.iletisim.gov.tr/images/uploads/icerik/_ikili/ee575f47-6128-45bc-bcf1-7720d9bfe44d_1.jpg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/article/div/a/div/img</value>
   </webElementXpaths>
</WebElementEntity>
