<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Videolar_entry__img lazyloaded</name>
   <tag></tag>
   <elementGuidId>cb4a1dcf-429f-492a-9ac9-583b45a3cba3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-container']/div[2]/div/article/div/div/div[2]/div/div/article/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.entry__img.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://img.youtube.com/vi/nMU_WoxukY8/mqdefault.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entry__img lazyloaded</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8 blog__content mb-72&quot;]/article[@class=&quot;entry mb-0&quot;]/div[@class=&quot;entry__article-wrap mt-0&quot;]/div[@class=&quot;entry__article  card-text  text-justify   bg-light&quot;]/div[@class=&quot;text-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/article[@class=&quot;entry card&quot;]/div[@class=&quot;entry__img-holder card__img-holder&quot;]/a[1]/div[@class=&quot;thumb-container thumb-70&quot;]/img[@class=&quot;entry__img lazyloaded&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div[2]/div/article/div/div/div[2]/div/div/article/div/a/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://img.youtube.com/vi/nMU_WoxukY8/mqdefault.jpg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
   </webElementXpaths>
</WebElementEntity>
