<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SEPETE EKLE_lazyloaded</name>
   <tag></tag>
   <elementGuidId>0a77f81a-5ce4-45e5-ac74-d252a84ec556</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div[3]/div/div/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> lazyloaded</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://i.idefix.com/cache/150x242-0/originals/0000000111687-1.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Savaşçı</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i.idefix.com/cache/150x242-0/originals/0000000111687-1.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;catPageContent&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-md-8 col-sm-12 col-xs-12&quot;]/div[@class=&quot;row productListBoxCont&quot;]/div[@class=&quot;col-md-12&quot;]/div[@id=&quot;container&quot;]/section[@class=&quot;full-content&quot;]/div[@id=&quot;container&quot;]/div[@class=&quot;no-margin productListNewBox boxes books clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-xl-3 col-lg-4 col-md-6 col-sm-6 col-xs-6-product catalogProductListNeOkusam itemlittleProduct datalayer-active&quot;]/div[@class=&quot;item product-box-alternative&quot;]/div[@class=&quot;product-box-alternative product-box productListNewBox cart-product-box&quot;]/div[@class=&quot;cart-product-box-view&quot;]/a[@class=&quot;product-image&quot;]/div[@class=&quot;image-area&quot;]/img[@class=&quot;lazyloaded&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div[3]/div/div/div/a/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Savaşçı']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a/div/img</value>
   </webElementXpaths>
</WebElementEntity>
