<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ins_Medya Tipi_iCheck-helper</name>
   <tag></tag>
   <elementGuidId>892a2a9a-772f-4269-a229-e40c4c8e23c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ins.iCheck-helper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='filter-media-type']/ul/li/a/span/div/ins</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ins</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iCheck-helper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-media-type&quot;)/ul[@class=&quot;MediaTypeList&quot;]/li[1]/a[@class=&quot;clearfix&quot;]/span[1]/div[@class=&quot;icheckbox_flat-grey hover&quot;]/ins[@class=&quot;iCheck-helper&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-media-type']/ul/li/a/span/div/ins</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ins</value>
   </webElementXpaths>
</WebElementEntity>
