<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ins_rn Puan_iCheck-helper</name>
   <tag></tag>
   <elementGuidId>27cba3fe-93c6-4d2b-9ab3-5763924c3dd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.icheckbox_flat-grey.hover > ins.iCheck-helper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='filter-media-point']/ul/li/a/span/div/ins</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ins</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iCheck-helper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-media-point&quot;)/ul[@class=&quot;RateList&quot;]/li[1]/a[@class=&quot;clearfix&quot;]/span[1]/div[@class=&quot;icheckbox_flat-grey hover&quot;]/ins[@class=&quot;iCheck-helper&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-media-point']/ul/li/a/span/div/ins</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[7]/div/div/div/div[2]/ul/li/a/span/div/ins</value>
   </webElementXpaths>
</WebElementEntity>
