<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_cars_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>8acb7a49-71c6-45a7-9a9b-af09fdfb55c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq27azBoWcQzCywy5jUr8qxhHarLTsuXEmRdQENyBDYCgRsgcXPCKWO5YFIjAJNClZLPTejoj2kTOlW8O0-cwA7GqLdvtw2eToySHnjfIkpht1QiP3Kn7CZ6aLiJZUkj_wjsMWBjjR8K3njtqpFq_3-MfaxzzVQYickY3U4aJ9fgawGHe0yGABArk4q-hd3JEi1lRPABj&amp;k=6Lfmm70ZAAAAADvPzM6OhZ8Adi40-78E-aYfc1ZS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Human verification - Stack Overflow/iframe_Customize settings_c-jw226jqrpn9t</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq27azBoWcQzCywy5jUr8qxhHarLTsuXEmRdQENyBDYCgRsgcXPCKWO5YFIjAJNClZLPTejoj2kTOlW8O0-cwA7GqLdvtw2eToySHnjfIkpht1QiP3Kn7CZ6aLiJZUkj_wjsMWBjjR8K3njtqpFq_3-MfaxzzVQYickY3U4aJ9fgawGHe0yGABArk4q-hd3JEi1lRPABj&amp;k=6Lfmm70ZAAAAADvPzM6OhZ8Adi40-78E-aYfc1ZS')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
